name: el_tooltip
description: ElTooltip, a smart positioned tooltip. Use it to display a widget inside a tooltip that you can personalize.
version: 2.2.1
repository: https://github.com/marcelogil/el_tooltip

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true